POST http://localhost:8080/v1/formula/save/7745
Content-Type: application/json;charset=utf-8

{
    "technology": "4",
    "default_detail": "{\"4RL\":0.97,\"5BL\":1.6,\"HGL\":0.66}",
    "deep_detail": "{\"4RL\":0.97,\"5BL\":1.6,\"HGL\":0.66}",
    "light_detail": "{\"4RL\":1.06,\"5BL\":1.92,\"HGL\":0.66}"
}